import { useCallback, useDeferredValue, useEffect, useMemo, useState } from "react";
import type { PersonaQuery } from "./api/personas";
import { Overview } from "./components/Overview";
import { PersonaDrawer } from "./components/PersonaDrawer";
import { PersonaFilters } from "./components/PersonaFilters";
import { PersonaTable } from "./components/PersonaTable";
import { Sidebar } from "./components/Sidebar";
import { Topbar } from "./components/Topbar";
import { usePersonas } from "./hooks/usePersonas";
import { countryName, genreLabel, humanize } from "./lib/format";
import type { PersonaSummary } from "./types/persona";
import "./App.css";

// Search what the user sees ("Hip-hop", "Software engineer"), not the raw keys ("hip_hop").
function matches(p: PersonaSummary, text: string): boolean {
  const haystack = [
    p.alias, p.id, p.country, countryName(p.country), humanize(p.occupation), p.jobTitle ?? "",
    humanize(p.archetype), humanize(p.lifeStage), ...p.topGenres.map(genreLabel),
  ].join(" ").toLowerCase();
  return haystack.includes(text);
}

function App() {
  // Server-side filters (sent to the API) and client-side search (applied in the browser).
  const [query, setQuery] = useState<PersonaQuery>({});
  const [search, setSearch] = useState("");
  // Lazy initializer: read the URL once on mount, so /#persona_000003 opens that persona.
  const [selectedId, setSelectedId] = useState<string | null>(() => window.location.hash.slice(1) || null);

  const state = usePersonas(query);

  // Typing stays responsive: the expensive filtering uses a deferred copy of the search text.
  const deferredSearch = useDeferredValue(search);
  const visible = useMemo(() => {
    if (state.status !== "success") return [];
    const text = deferredSearch.trim().toLowerCase();
    return text ? state.data.personas.filter((p) => matches(p, text)) : state.data.personas;
  }, [state, deferredSearch]);

  // Keep the URL in sync with the open persona, so the view can be shared or reloaded.
  useEffect(() => {
    const url = selectedId ? `#${selectedId}` : window.location.pathname + window.location.search;
    window.history.replaceState(null, "", url);
  }, [selectedId]);

  // Stable function identity, so the drawer's effect does not re-subscribe on every render.
  const closeDrawer = useCallback(() => setSelectedId(null), []);

  const filtersLabel = [query.lifeStage && humanize(query.lifeStage), query.country].filter(Boolean).join(" · ");

  return (
    <div className="shell">
      <Sidebar />
      <div className="main">
        <Topbar search={search} onSearchChange={setSearch} />
        <main className="page">
          <div className="page-head">
            <div>
              <h1>Personas</h1>
              <p className="muted">
                Synthetic listeners generated by the simulation{filtersLabel && ` · ${filtersLabel}`}
              </p>
            </div>
          </div>

          <Overview personas={visible} />

          <PersonaFilters value={query} onChange={setQuery} resultCount={state.status === "success" ? visible.length : null} />
          <PersonaTable state={state} personas={visible} selectedId={selectedId} onSelect={setSelectedId} />
        </main>
      </div>
      <PersonaDrawer personaId={selectedId} onClose={closeDrawer} />
    </div>
  );
}

export default App;
